feat: update docs to include expiration date
Axle-Labs/axle pull request #74
Opened 2024-12-19 17:39 UTC by audrey-axle

2024-12-19 17:39 UTC, audrey-axle commented on docs/openapi.yml
> +                          rental-covered-for-collision:
noticed this typo so updated

2024-12-20 17:03 UTC, Sshatzkin requested changes

2024-12-20 17:03 UTC, Sshatzkin commented on docs/guides/policy-validation.mdx
> +This Rule requires additional input to be evaluated. Specifically, the `input` must include a `date` property as a string, representing the date to compare against the policy's expiration date.
What are the requirements around the date format? We use ISO 8601 but it's possible we could build this feature flexibly to allow customers to submit a few supported date formats.

Related - What validation do we do on our end to ensure that the input we receive is in the correct format and notify the client if it is not? We should ensure that we have this kind of input validation in the code and mention somewhere in the docs what kind of error handling they should expect to see.

2024-12-20 17:33 UTC, audrey-axle commented on docs/openapi.yml
> +                oneOf:
Hmm, I'm seeing it and running it right now. Are you looking in the right place?
![Screenshot 2024-12-20 at 10 32 56 AM](https://github.com/user-attachments/assets/1487e752-551a-4fc8-acdc-40ff176bd203)

2024-12-20 17:34 UTC, audrey-axle commented on docs/guides/policy-validation.mdx
> +  <Accordion title="Policy Expiration Date Comparison">
Sure, although I like how it parallels the text above, as we have three paragraphs above the first one on policy-active, the second on rental coverage, the third on expiration date, and that's the same order as these accordion groups. Is there a reason to put it before or after? Just because the rental one is more complicated and longer so if a reader expands the accordion they might not see the expiration-date rule below?

2024-12-20 17:37 UTC, audrey-axle commented on docs/guides/policy-validation.mdx
> +This Rule requires additional input to be evaluated. Specifically, the `input` must include a `date` property as a string, representing the date to compare against the policy's expiration date.
Right now the only validation we do is that the input is a string, but we can make that stricter to accept a date in the format ISO 8601. I'm happy to make that change and then make a note here that that's what's expected and give examples. If it's not the correct format, the typical 4xx incorrect input validation will be thrown.

2024-12-20 20:47 UTC, Sshatzkin approved these changes

2024-12-20 20:47 UTC, Sshatzkin commented on docs/openapi.yml
> +                oneOf:
Oh I see, looks fine. I was looking at the input code box on the top right, where there used to be some sort of example rule in the body, but I think this looks good.

2024-12-20 22:09 UTC, merged